// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCrJ5Wi5hhiVp3nxi7HtE0Bj0TfQu5Am4',
    appId: '1:696374154522:web:bab7475ea508a7761e48a3',
    messagingSenderId: '696374154522',
    projectId: 'slide-puzzle-5228c',
    authDomain: 'slide-puzzle-5228c.firebaseapp.com',
    storageBucket: 'slide-puzzle-5228c.appspot.com',
    measurementId: 'G-91GCSN3N4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSmrIPquDbwlA9VXKN3IovGilrD59hd-o',
    appId: '1:696374154522:android:abebad06e79eb47a1e48a3',
    messagingSenderId: '696374154522',
    projectId: 'slide-puzzle-5228c',
    storageBucket: 'slide-puzzle-5228c.appspot.com',
  );
}
